# Setup
title: Kavel Rao
# tagline:             ''
description: "Kavel's website"
url: https://kavelrao.dev
baseurl: ""
permalink: pretty

markdown: kramdown
kramdown:
  math_engine: mathjax

# About/contact
author:
  name: Kavel Rao
  email: rao.kavel@gmail.com
  linkedin: kavel-rao
  github: kavelrao

# Gems
plugins:
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
